<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AwesomeAssertions" Version="9.4.0" />
		<PackageReference Include="AwesomeAssertions.Analyzers" Version="9.0.8">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MSTest" Version="3.8.3"/>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ChessSDK\ChessSDK.csproj" />
	</ItemGroup>

</Project>
